TRAIN:
  ENABLE: True
  DATASET: Kinetics
  BATCH_SIZE: 32
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]
  PATH_TO_DATA_DIR: data/kinetics_400/
  USE_RAND_AUGMENT: False
  RE_PROB: 0.0
  USE_REPEATED_AUG: False
  USE_RANDOM_RESIZE_CROPS: False
  COLORJITTER: True
  GRAYSCALE: False
  GAUSSIAN: False
  PATH_LABEL_SEPARATOR: ","
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 20, 30]
  MAX_EPOCH: 35
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-2
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: adamw
  USE_MIXED_PRECISION: True
  SMOOTHING: 0.2
SLOWFAST:
  ALPHA: 8
VIT:
  PATCH_SIZE: 16
  PATCH_SIZE_TEMP: 2
  CHANNELS: 3
  EMBED_DIM: 768
  DEPTH: 12
  NUM_HEADS: 12
  MLP_RATIO: 4
  QKV_BIAS: True
  VIDEO_INPUT: True
  TEMPORAL_RESOLUTION: 8
  USE_MLP: True
  DROP: 0.0
  POS_DROPOUT: 0.0
  DROP_PATH: 0.2
  IM_PRETRAINED: True
  HEAD_DROPOUT: 0.0
  HEAD_ACT: tanh
  PRETRAINED_WEIGHTS: vit_1k
  ATTN_LAYER: trajectory
MODEL:
  NUM_CLASSES: 400
  ARCH: slow
  MODEL_NAME: VisionTransformer
  LOSS_FUNC: cross_entropy
TEST:
  ENABLE: True
  DATASET: Kinetics
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 4
RNG_SEED: 0
OUTPUT_DIR: ./test

TENSORBOARD:
  ENABLE: True
  CATEGORIES_PATH: ./csv_ytid/parent_child.json
  CLASS_NAMES_PATH: ./csv_ytid/label_mapping.json
  CONFUSION_MATRIX: 
    ENABLE: True
    FIGSIZE: [8, 8]
    SUBSET_PATH: ./csv_ytid/test.csv

  HISTOGRAM:
    ENABLE: True
    FIGSIZE: [8, 8]
    SUBSET_PATH: 
    TOPK: 10
  LOG_DIR: log_test
  MODEL_VIS:
    ACTIVATIONS: True
    COLORMAP: Pastel2
    ENABLE: True
    GRAD_CAM:
      COLORMAP: viridis
      ENABLE: True
      LAYER_LIST: []
      USE_TRUE_LABEL: False
    INPUT_VIDEO: False
    LAYER_LIST: []
    MODEL_WEIGHTS: False
    TOPK_PREDS: 1
  PREDICTIONS_PATH: 
  WRONG_PRED_VIS:
    ENABLE: True
    SUBSET_PATH: 
    TAG: Incorrectly classified videos.
